final List<String> bangaloreLocations = [
  "MG Road, Bengaluru, Karnataka 560001, India",
  "Majestic (Kempegowda Bus Station), Gandhi Nagar, Bengaluru, Karnataka 560009, India",
  "Electronic City, Bengaluru, Karnataka 560100, India",
  "Whitefield, Bengaluru, Karnataka 560066, India",
  "Koramangala, Bengaluru, Karnataka 560034, India",
  "Indiranagar, Bengaluru, Karnataka 560038, India",
  "Marathahalli, Bengaluru, Karnataka 560037, India",
  "Jayanagar, Bengaluru, Karnataka 560041, India",
  "BTM Layout, Bengaluru, Karnataka 560076, India",
  "Hebbal, Bengaluru, Karnataka 560024, India",
  "Yeshwanthpur, Bengaluru, Karnataka 560022, India",
  "KR Puram, Bengaluru, Karnataka 560036, India",
  "Banashankari, Bengaluru, Karnataka 560085, India",
  "Basavanagudi, Bengaluru, Karnataka 560004, India",
  "Richmond Town, Bengaluru, Karnataka 560025, India",
  "JP Nagar, Bengaluru, Karnataka 560078, India",
  "Ulsoor, Bengaluru, Karnataka 560008, India",
  "Hosur Road, Bengaluru, Karnataka 560030, India",
  "Bellandur, Bengaluru, Karnataka 560103, India",
  "Kengeri, Bengaluru, Karnataka 560060, India",
  "Rajajinagar, Bengaluru, Karnataka 560010, India",
  "Malleswaram, Bengaluru, Karnataka 560003, India",
  "Vidyaranyapura, Bengaluru, Karnataka 560097, India",
  "HBR Layout, Bengaluru, Karnataka 560043, India",
  "HRBR Layout, Bengaluru, Karnataka 560043, India",
  "Nagawara, Bengaluru, Karnataka 560045, India",
  "Kammanahalli, Bengaluru, Karnataka 560084, India",
  "Hennur, Bengaluru, Karnataka 560043, India",
  "Vasanth Nagar, Bengaluru, Karnataka 560052, India",
  "Shivajinagar, Bengaluru, Karnataka 560051, India",
  "Cunningham Road, Bengaluru, Karnataka 560052, India",
  "Fraser Town, Bengaluru, Karnataka 560005, India",
  "Brigade Road, Bengaluru, Karnataka 560001, India",
  "Commercial Street, Bengaluru, Karnataka 560001, India",
  "Lalbagh, Bengaluru, Karnataka 560004, India",
  "Cubbon Park, Bengaluru, Karnataka 560001, India",
  "Bannerghatta Road, Bengaluru, Karnataka 560076, India",
  "Hulimavu, Bengaluru, Karnataka 560076, India",
  "Bommanahalli, Bengaluru, Karnataka 560068, India",
  "Singasandra, Bengaluru, Karnataka 560068, India",
  "Anekal, Bengaluru, Karnataka 562106, India",
  "Yelahanka, Bengaluru, Karnataka 560064, India",
  "Bagalur, Bengaluru, Karnataka 562149, India",
  "Jakkur, Bengaluru, Karnataka 560064, India",
  "Sahakar Nagar, Bengaluru, Karnataka 560092, India",
  "Kodigehalli, Bengaluru, Karnataka 560092, India",
  "Peenya, Bengaluru, Karnataka 560058, India",
  "Nagasandra, Bengaluru, Karnataka 560073, India",
  "T Dasarahalli, Bengaluru, Karnataka 560057, India",
  "Chickpet, Bengaluru, Karnataka 560053, India",
  "Gandhi Bazaar, Bengaluru, Karnataka 560004, India",
  "Vijayanagar, Bengaluru, Karnataka 560040, India",
  "Nagarbhavi, Bengaluru, Karnataka 560072, India",
  "Kumaraswamy Layout, Bengaluru, Karnataka 560078, India",
  "Kanakapura Road, Bengaluru, Karnataka 560082, India",
  "Sarjapur Road, Bengaluru, Karnataka 560035, India",
  "Harlur, Bengaluru, Karnataka 560102, India",
  "HSR Layout, Bengaluru, Karnataka 560102, India",
  "Agara, Bengaluru, Karnataka 560102, India",
  "Kaikondrahalli, Bengaluru, Karnataka 560035, India",
  "Kasavanahalli, Bengaluru, Karnataka 560035, India",
  "Varthur, Bengaluru, Karnataka 560087, India",
  "Ramamurthy Nagar, Bengaluru, Karnataka 560016, India",
  "TC Palya, Bengaluru, Karnataka 560036, India",
  "KR Market, Bengaluru, Karnataka 560002, India",
  "Bangalore University, Bengaluru, Karnataka 560056, India",
  "Kumbalgodu, Bengaluru, Karnataka 560074, India",
  "Bidadi, Bengaluru, Karnataka 562109, India",
  "Nelamangala, Bengaluru, Karnataka 562123, India",
  "Tumkur Road, Bengaluru, Karnataka 560073, India",
  "Magadi Road, Bengaluru, Karnataka 560023, India",
  "Hosakote, Bengaluru, Karnataka 562114, India",
  "Devanahalli, Bengaluru, Karnataka 562110, India",
  "Kempegowda International Airport, Bengaluru, Karnataka 560300, India",
  "Chikkaballapur, Karnataka 562101, India",
  "Gunjur, Bengaluru, Karnataka 560087, India",
  "Hoskote Industrial Area, Bengaluru, Karnataka 562114, India",
  "Banaswadi, Bengaluru, Karnataka 560043, India",
  "Lingarajapuram, Bengaluru, Karnataka 560084, India",
  "Kalyan Nagar, Bengaluru, Karnataka 560043, India",
  "Hegde Nagar, Bengaluru, Karnataka 560077, India",
  "Thanisandra, Bengaluru, Karnataka 560077, India",
  "Rachenahalli, Bengaluru, Karnataka 560077, India",
  "Kaggadasapura, Bengaluru, Karnataka 560093, India",
  "CV Raman Nagar, Bengaluru, Karnataka 560093, India",
  "Baiyappanahalli, Bengaluru, Karnataka 560038, India",
  "Old Madras Road, Bengaluru, Karnataka 560038, India",
  "Bennigana Halli, Bengaluru, Karnataka 560038, India",
  "Gopalan Mall, Bengaluru, Karnataka 560016, India",
  "ITPL, Whitefield, Bengaluru, Karnataka 560066, India",
  "Brookefield, Bengaluru, Karnataka 560037, India",
  "Doddanekkundi, Bengaluru, Karnataka 560037, India",
  "Hoodi, Bengaluru, Karnataka 560048, India",
  "Thubarahalli, Bengaluru, Karnataka 560066, India",
  "Munnekolala, Bengaluru, Karnataka 560037, India",
  "Kadugodi, Bengaluru, Karnataka 560067, India",
  "Hope Farm Junction, Bengaluru, Karnataka 560066, India",
  "Madiwala, Bengaluru, Karnataka 560068, India",
  "Anand Rao Circle, Bengaluru, Karnataka 560009, India",
  "Chamarajpet, Bengaluru, Karnataka 560018, India",
  "Wilson Garden, Bengaluru, Karnataka 560027, India",
  "Sunkadakatte, Bengaluru, Karnataka 560091, India",
  "Malleshpalya, Bengaluru, Karnataka 560075, India",
  "Attibele, Bengaluru, Karnataka 562107, India",
  "Domlur, Bengaluru, Karnataka 560071, India",
  "Basaveshwaranagar, Bengaluru, Karnataka 560079, India",
  "Girinagar, Bengaluru, Karnataka 560085, India",
  "Gokula Extension, Bengaluru, Karnataka 560054, India",
  "Mallathahalli, Bengaluru, Karnataka 560056, India",
  "Gavipuram, Bengaluru, Karnataka 560019, India",

  // Colleges in Bengaluru
  "PES University, Banashankari, Bengaluru, Karnataka 560085, India",
  "RV College of Engineering, Mysore Road, Bengaluru, Karnataka 560059, India",
  "BMS College of Engineering, Basavanagudi, Bengaluru, Karnataka 560019, India",
  "MS Ramaiah Institute of Technology, Mathikere, Bengaluru, Karnataka 560054, India",
  "Christ University, Hosur Road, Bengaluru, Karnataka 560029, India",
  "Jain University, Jayanagar, Bengaluru, Karnataka 560011, India",
  "Dayananda Sagar College of Engineering, Kumaraswamy Layout, Bengaluru, Karnataka 560078, India",
  "New Horizon College of Engineering, Marathahalli, Bengaluru, Karnataka 560103, India",
  "Sir M. Visvesvaraya Institute of Technology, Yelahanka, Bengaluru, Karnataka 562157, India",
  "CMR Institute of Technology, Kundalahalli, Bengaluru, Karnataka 560037, India",
  "Acharya Institute of Technology, Soladevanahalli, Bengaluru, Karnataka 560107, India",
  "Oxford College of Engineering, Bommanahalli, Bengaluru, Karnataka 560068, India",
  "Reva University, Kattigenahalli, Yelahanka, Bengaluru, Karnataka 560064, India",
  "Presidency University, Itgalpur, Rajanakunte, Bengaluru, Karnataka 560064, India",
  "SJB Institute of Technology, Kengeri, Bengaluru, Karnataka 560060, India",
  "Global Academy of Technology, Rajarajeshwari Nagar, Bengaluru, Karnataka 560098, India",
  "Nitte Meenakshi Institute of Technology, Yelahanka, Bengaluru, Karnataka 560064, India",
  "Rajarajeswari College of Engineering, Mysore Road, Bengaluru, Karnataka 560074, India",
  "ISBR Business School, Electronic City, Bengaluru, Karnataka 560100, India",
  "Garden City University, KR Puram, Bengaluru, Karnataka 560049, India",
  "T John Institute of Technology, Bannerghatta Road, Bengaluru, Karnataka 560083, India",
  "CMR University, Bagalur, Bengaluru, Karnataka 562149, India",
  "Mount Carmel College, Vasanth Nagar, Bengaluru, Karnataka 560052, India",
  "St. Joseph’s College, Langford Road, Bengaluru, Karnataka 560027, India",
  "Bangalore Institute of Technology, KR Road, Bengaluru, Karnataka 560004, India",
  "East Point College of Engineering, Avalahalli, Bengaluru, Karnataka 560049, India",
  "RNS Institute of Technology, RR Nagar, Bengaluru, Karnataka 560098, India",
  "Cambridge Institute of Technology, KR Puram, Bengaluru, Karnataka 560036, India",
  "BNM Institute of Technology, Banashankari, Bengaluru, Karnataka 560070, India",
  "PES Institute of Technology South Campus, Electronic City, Bengaluru, Karnataka 560100, India",
  "MS Ramaiah College of Arts, Science & Commerce, MSR Nagar, Bengaluru, Karnataka 560054, India",
  "Don Bosco Institute of Technology, Kumbalagodu, Bengaluru, Karnataka 560074, India",
  "Sri Venkateshwara College of Engineering, Vidyanagar, Bengaluru, Karnataka 562157, India",
  "Brindavan College of Engineering, Yelahanka, Bengaluru, Karnataka 560063, India",
  "Gopalan College of Engineering, Whitefield, Bengaluru, Karnataka 560066, India",
  "Sri Krishna Institute of Technology, Peenya, Bengaluru, Karnataka 560090, India",
  "Sri Sai Ram College of Engineering, Anekal, Bengaluru, Karnataka 562106, India",
  "Bangalore Medical College, KR Market, Bengaluru, Karnataka 560002, India",
  "Dr. Ambedkar Institute of Technology, Nagarbhavi, Bengaluru, Karnataka 560072, India",
  "Sri Bhagawan Mahaveer Jain College, JC Road, Bengaluru, Karnataka 560027, India",
  "East West Institute of Technology, Anjananagar, Bengaluru, Karnataka 560091, India",
  "Sambhram Institute of Technology, MS Palya, Bengaluru, Karnataka 560097, India",
  "Indian Institute of Science (IISc), CV Raman Ave, Bengaluru, Karnataka 560012, India",
  "Alliance University, Chandapura-Anekal Road, Bengaluru, Karnataka 562106, India",
  "Amrita School of Engineering, Kasavanahalli, Bengaluru, Karnataka 560035, India",
  "Indian Institute of Management Bangalore (IIMB), Bannerghatta Road, Bengaluru, Karnataka 560076, India",
  "Bangalore University, Mysore Road, Bengaluru, Karnataka 560056, India",
  "CMR Law School, OMBR Layout, Bengaluru, Karnataka 560043, India",
  "Kristu Jayanti College, K. Narayanapura, Bengaluru, Karnataka 560077, India",
  "Ramaiah University of Applied Sciences, Peenya, Bengaluru, Karnataka 560058, India",
  "Seshadripuram College, Yelahanka, Bengaluru, Karnataka 560064, India",
  "GITAM University, Nagadenahalli, Bengaluru, Karnataka 562163, India",
  "National Law School of India University (NLSIU), Nagarbhavi, Bengaluru, Karnataka 560072, India",
  "HKBK College of Engineering, Nagawara, Bengaluru, Karnataka 560045, India",
  "T John College, Gottigere, Bengaluru, Karnataka 560083, India",
  "CMR Institute of Management Studies, HRBR Layout, Bengaluru, Karnataka 560043, India",
  "Vijaya College, Basavanagudi, Bengaluru, Karnataka 560004, India",
  "KLE Society's Law College, Yeswanthpur, Bengaluru, Karnataka 560022, India"
];
