name: ridealong
description: "A new Flutter project."
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  yaml: ^3.1.2
  cupertino_icons: ^1.0.8
  firebase_core: ^3.9.0
  firebase_auth: ^5.3.4
  cloud_firestore: ^5.6.0
  firebase_storage: ^12.3.7
  firebase_messaging: ^15.1.6

  http: ^0.13.6
  provider: ^6.0.0
  geolocator: ^10.1.0
  google_maps_flutter: ^2.2.3
 
  google_maps_webservice: ^0.0.20-nullsafety.5
  shared_preferences: ^2.1.0
  fluttertoast: ^8.2.1
  url_launcher: ^6.1.7
  syncfusion_flutter_calendar: ^20.3.56
  table_calendar: ^3.0.9
  image_picker: ^0.8.7+4
  lottie: ^2.2.0
  intl: ^0.18.0
  permission_handler: ^11.1.0
  google_sign_in: ^5.4.0
  geocoding: ^2.0.1
  carousel_slider: ^4.2.1
  flutter_dotenv: ^5.2.1
  location: ^5.0.3
  google_places_flutter: ^2.0.6
  flutter_map: ^4.0.0
  mapbox_search: ^3.2.0
  latlong2: ^0.8.2
  flutter_polyline_points: ^1.0.0
  # contacts_service: ^0.6.3
  # flutter_sms: ^2.3.2
  # device_info_plus: ^9.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/travel_animation.json
    - assets/Airplane_animation.json
    - assets/packing_list.json
    - assets/ride.json
